### ISSUE TITLE
Yarn test error

### ISSUE THREAD

**Issue by Valorised** [Microsoft/PowerBI-visuals-NetworkNavigator#25]
Hello,

I am trying to compile the repo but I'm facing errors upon running the "yarn test" command.
npm version : 5.0.3
Node.js version : 8.1.1

Here is what it says (I have attached screenshots of the error lines you see below at the bottom of the post)

`@essex/network-navigator: webpack: bundle is now VALID.
@essex/network-navigator: 19 06 2017 11:38:20.733:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#Vzhv8M2Q2dvoMwvxAAAA with id 57074436
                          PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 22 of 22 SUCCESS (0.211 secs / 0.283 secs)
@essex/network-navigator:
@essex/network-navigator: > @essex/network-navigator@0.11.2 docs C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator
@essex/network-navigator: > typedoc --out docs --ignoreCompilerErrors ./ --externalPattern **/node_modules/**/*.* --exclude **/src/**/*.spec.ts > /dev/null || exit 1
@essex/network-navigator:
@essex/network-navigator: Le chemin d'acc�s sp�cifi� est introuvable.
@essex/network-navigator: npm ERR! code ELIFECYCLE
@essex/network-navigator: npm ERR! errno 1
@essex/network-navigator: npm ERR! @essex/network-navigator@0.11.2 docs: `typedoc --out docs --ignoreCompilerErrors ./ --externalPattern **/node_modules/**/*.* --exclude **/src/**/*.spec.ts > /dev/null || exit 1`
@essex/network-navigator: npm ERR! Exit status 1
@essex/network-navigator: npm ERR!
@essex/network-navigator: npm ERR! Failed at the @essex/network-navigator@0.11.2 docs script.
@essex/network-navigator: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@essex/network-navigator:
@essex/network-navigator: npm ERR! A complete log of this run can be found in:
@essex/network-navigator: npm ERR!     C:\Users\vchau\AppData\Roaming\npm-cache\_logs\2017-06-19T09_38_22_391Z-debug.log
@essex/network-navigator: ERROR: "docs" exited with 1.
@essex/network-navigator: npm ERR! code ELIFECYCLE
@essex/network-navigator: npm ERR! errno 1
@essex/network-navigator: npm ERR! @essex/network-navigator@0.11.2 verify: `npm run clean && tsc && npm-run-all lint karma:once docs`
@essex/network-navigator: npm ERR! Exit status 1
@essex/network-navigator: npm ERR!
@essex/network-navigator: npm ERR! Failed at the @essex/network-navigator@0.11.2 verify script.
@essex/network-navigator: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@essex/network-navigator:
@essex/network-navigator: npm ERR! A complete log of this run can be found in:
@essex/network-navigator: npm ERR!     C:\Users\vchau\AppData\Roaming\npm-cache\_logs\2017-06-19T09_38_22_463Z-debug.log
@essex/network-navigator: npm ERR! code ELIFECYCLE
@essex/network-navigator: npm ERR! errno 1
@essex/network-navigator: npm ERR! @essex/network-navigator@0.11.2 test: `npm run verify`
@essex/network-navigator: npm ERR! Exit status 1
@essex/network-navigator: npm ERR!
@essex/network-navigator: npm ERR! Failed at the @essex/network-navigator@0.11.2 test script.
@essex/network-navigator: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@essex/network-navigator:
@essex/network-navigator: npm ERR! A complete log of this run can be found in:
@essex/network-navigator: npm ERR!     C:\Users\vchau\AppData\Roaming\npm-cache\_logs\2017-06-19T09_38_22_518Z-debug.log
NpmUtilities.runScriptInPackageStreaming("test", [], {"_package":{"name":"@essex/network-navigator","version":"0.11.2","description":"","main...)
Command exited with status 1: npm run test
Errored while running RunCommand.execute
Command exited with status 1: npm run test
error Command failed with exit code 1.`

Inside 2017-06-19T09_38_22_391Z-debug.log 

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\vchau\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'docs' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose run-script [ 'predocs', 'docs', 'postdocs' ]
5 info lifecycle @essex/network-navigator@0.11.2~predocs: @essex/network-navigator@0.11.2
6 silly lifecycle @essex/network-navigator@0.11.2~predocs: no script for predocs, continuing
7 info lifecycle @essex/network-navigator@0.11.2~docs: @essex/network-navigator@0.11.2
8 verbose lifecycle @essex/network-navigator@0.11.2~docs: unsafe-perm in lifecycle true
9 verbose lifecycle @essex/network-navigator@0.11.2~docs: PATH: C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator\node_modules\.bin;C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator\node_modules\.bin;C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator\node_modules\.bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\node_modules\.bin;C:\Users\vchau\AppData\Local\Yarn\config\link\node_modules\.bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\node_modules\.bin;C:\Users\vchau\AppData\Local\Yarn\config\link\node_modules\.bin;C:\Users\vchau\AppData\Local\Yarn\bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\vchau\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\vchau\AppData\Local\Yarn\bin;C:\Users\vchau\AppData\Roaming\npm
10 verbose lifecycle @essex/network-navigator@0.11.2~docs: CWD: C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator
11 silly lifecycle @essex/network-navigator@0.11.2~docs: Args: [ '/d /s /c',
11 silly lifecycle   'typedoc --out docs --ignoreCompilerErrors ./ --externalPattern **/node_modules/**/*.* --exclude **/src/**/*.spec.ts > /dev/null || exit 1' ]
12 silly lifecycle @essex/network-navigator@0.11.2~docs: Returned: code: 1  signal: null
13 info lifecycle @essex/network-navigator@0.11.2~docs: Failed to exec docs script
14 verbose stack Error: @essex/network-navigator@0.11.2 docs: `typedoc --out docs --ignoreCompilerErrors ./ --externalPattern **/node_modules/**/*.* --exclude **/src/**/*.spec.ts > /dev/null || exit 1`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid @essex/network-navigator@0.11.2
16 verbose cwd C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vchau\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "docs"
19 verbose node v8.1.1
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error @essex/network-navigator@0.11.2 docs: `typedoc --out docs --ignoreCompilerErrors ./ --externalPattern **/node_modules/**/*.* --exclude **/src/**/*.spec.ts > /dev/null || exit 1`
23 error Exit status 1
24 error Failed at the @essex/network-navigator@0.11.2 docs script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]`

Inside 2017-06-19T09_38_22_463Z-debug.log
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\vchau\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'verify' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose run-script [ 'preverify', 'verify', 'postverify' ]
5 info lifecycle @essex/network-navigator@0.11.2~preverify: @essex/network-navigator@0.11.2
6 silly lifecycle @essex/network-navigator@0.11.2~preverify: no script for preverify, continuing
7 info lifecycle @essex/network-navigator@0.11.2~verify: @essex/network-navigator@0.11.2
8 verbose lifecycle @essex/network-navigator@0.11.2~verify: unsafe-perm in lifecycle true
9 verbose lifecycle @essex/network-navigator@0.11.2~verify: PATH: C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator\node_modules\.bin;C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator\node_modules\.bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\node_modules\.bin;C:\Users\vchau\AppData\Local\Yarn\config\link\node_modules\.bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\node_modules\.bin;C:\Users\vchau\AppData\Local\Yarn\config\link\node_modules\.bin;C:\Users\vchau\AppData\Local\Yarn\bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\vchau\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\vchau\AppData\Local\Yarn\bin;C:\Users\vchau\AppData\Roaming\npm
10 verbose lifecycle @essex/network-navigator@0.11.2~verify: CWD: C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator
11 silly lifecycle @essex/network-navigator@0.11.2~verify: Args: [ '/d /s /c',
11 silly lifecycle   'npm run clean && tsc && npm-run-all lint karma:once docs' ]
12 silly lifecycle @essex/network-navigator@0.11.2~verify: Returned: code: 1  signal: null
13 info lifecycle @essex/network-navigator@0.11.2~verify: Failed to exec verify script
14 verbose stack Error: @essex/network-navigator@0.11.2 verify: `npm run clean && tsc && npm-run-all lint karma:once docs`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid @essex/network-navigator@0.11.2
16 verbose cwd C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vchau\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "verify"
19 verbose node v8.1.1
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error @essex/network-navigator@0.11.2 verify: `npm run clean && tsc && npm-run-all lint karma:once docs`
23 error Exit status 1
24 error Failed at the @essex/network-navigator@0.11.2 verify script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
`

Inside 2017-06-19T09_38_22_518Z-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\vchau\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle @essex/network-navigator@0.11.2~pretest: @essex/network-navigator@0.11.2
6 silly lifecycle @essex/network-navigator@0.11.2~pretest: no script for pretest, continuing
7 info lifecycle @essex/network-navigator@0.11.2~test: @essex/network-navigator@0.11.2
8 verbose lifecycle @essex/network-navigator@0.11.2~test: unsafe-perm in lifecycle true
9 verbose lifecycle @essex/network-navigator@0.11.2~test: PATH: C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator\node_modules\.bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\node_modules\.bin;C:\Users\vchau\AppData\Local\Yarn\config\link\node_modules\.bin;C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\node_modules\.bin;C:\Users\vchau\AppData\Local\Yarn\config\link\node_modules\.bin;C:\Users\vchau\AppData\Local\Yarn\bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Yarn\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\vchau\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\vchau\AppData\Local\Yarn\bin;C:\Users\vchau\AppData\Roaming\npm
10 verbose lifecycle @essex/network-navigator@0.11.2~test: CWD: C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator
11 silly lifecycle @essex/network-navigator@0.11.2~test: Args: [ '/d /s /c', 'npm run verify' ]
12 silly lifecycle @essex/network-navigator@0.11.2~test: Returned: code: 1  signal: null
13 info lifecycle @essex/network-navigator@0.11.2~test: Failed to exec test script
14 verbose stack Error: @essex/network-navigator@0.11.2 test: `npm run verify`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\vchau\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid @essex/network-navigator@0.11.2
16 verbose cwd C:\Users\vchau\Desktop\PowerBI_Valentin\PowerBI-visuals-NetworkNavigator-develop\packages\network-navigator
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vchau\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
19 verbose node v8.1.1
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error @essex/network-navigator@0.11.2 test: `npm run verify`
23 error Exit status 1
24 error Failed at the @essex/network-navigator@0.11.2 test script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
`

Note : I noticed that the packages aren't updated to the wanted version when I display the packages version with the "yarn outdated" command

It's been since 15/06/2017 that I've been trying to compile this repo to no avail, any help will be appreciated !

![yarn test](https://user-images.githubusercontent.com/29540110/27282132-fb118d98-54ee-11e7-90d4-d4b9434e9ea8.png)
![2017-06-19t09_38_22_391z-debug log](https://user-images.githubusercontent.com/29540110/27282134-fd1f39dc-54ee-11e7-81c6-83e7eb57a8ce.png)
![2017-06-19t09_38_22_463z-debug log](https://user-images.githubusercontent.com/29540110/27282136-ff2daf92-54ee-11e7-9ddd-47a38ad6cc3a.png)
![2017-06-19t09_38_22_518z-debug log](https://user-images.githubusercontent.com/29540110/27282137-00c3d1ce-54ef-11e7-8823-ef1e1b82c995.png)

**Comment by stopyoukid** [comment]
I believe this is because you are building on Windows, would you mind testing against the `fix-windows-build` branch to see if it fixes your issues?

**Comment by Valorised** [comment]
Thank you for your quick reply. I am currently not at work and will try that out tomorrow (which will be in about 15 hours), I'll be sure to keep you updated !

**Comment by stopyoukid** [comment]
So, I've merged this into develop, please use that instead.

**Comment by Valorised** [comment]
It worked ! Thank you very much ! May I ask where are the pbiviz.json & capabilities.json files located ? I can't find them anywhere.

**Comment by stopyoukid** [comment]
No problem, glad it worked 😄. This visual has an old build system that was created *well* before the pbiviz tools were released, so there is no pbiviz file.  

If you are looking to change the name/guid of the project, look here: https://github.com/Microsoft/PowerBI-visuals-NetworkNavigator/blob/develop/packages/network-navigator-powerbi/src/build.json#L4-L6

The capabilities json file in this project is actually in a .ts file here: https://github.com/Microsoft/PowerBI-visuals-NetworkNavigator/blob/develop/packages/network-navigator-powerbi/src/capabilities.ts

A hint, if you are trying to add formatting pane settings, we have some special decorators which do auto parsing of settings for you, for example: https://github.com/Microsoft/PowerBI-visuals-NetworkNavigator/blob/develop/packages/network-navigator-powerbi/src/state.ts#L45-L51.  This will add a boolean setting (which just creates a toggle switch in PowerBI), and if you look through the rest of that file, you can see there are several types of settings.

When the settings values change in PowerBI, the settings object gets parsed here: https://github.com/Microsoft/PowerBI-visuals-NetworkNavigator/blob/develop/packages/network-navigator-powerbi/src/NetworkNavigatorVisual.ts#L340 .  

After this point, you can check `this._internalState.<YOUR SETTING NAME>`, it will contain the current setting. You also don't need to worry about enumerateObjectInstances, it is taken care of for you: https://github.com/Microsoft/PowerBI-visuals-NetworkNavigator/blob/develop/packages/network-navigator-powerbi/src/NetworkNavigatorVisual.ts#L251

Hope this helps.

**Comment by Valorised** [comment]
Thank you for the quick reply once again :D. Yes I figured this visual had an odd architecture !

Right now your hints are pretty much cryptic to me but I won't give up, I will figure it out !
